### ISSUE TITLE
Namespaced components produce a warning

### ISSUE THREAD

**Issue by jedrichards** [necolas/postcss-bem-linter#14]
Hey guys

Love the work you're doing on this. 

I discovered that components named as per the optional SuitCSS [namespace](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md#namespace-optional) spec produce a warning in the output (if not an outright fail).

E.g. a component named `ns-ComponentName` produces the warning,

```
WARNING: invalid component name in definition
```

Is this by design? Or would you be open to PRs fixing the above?

**Comment by necolas** [comment]
> would you be open to PRs fixing the above?

yeah sure

**Comment by jedrichards** [comment]
I've tried a couple of times to sit down and do this, but keep on getting weird interactions between the various regex you have setup in different files and then giving up. Regex is admittedly not something I spend a lot of time wrangling with. Realistically I'm not going to get round to it, feel free to close or keep open if you think its important and someone else may get round to it. Sorry.

**Comment by davidtheclark** [comment]
I have a branch ready to fix this problem but realized that it will have a few conflicts with pending PR https://github.com/necolas/postcss-bem-linter/pull/18/files — so once that one gets merged or rejected, I can get offer a solution to this issue.

**Comment by davidtheclark** [comment]
The solution I was thinking about was to add a second parameter that is options, and `namespace` will be an option that the `'suit'` pattern pays attention to. This would change function signature, then, so you've got `bemLinter(pattern, options)`. That options object might include other stuff for other patterns. Does this seem like a good solution to you @necolas ? I can work on a PR for it tonight or tomorrow.
