### ISSUE TITLE
Change `selector` to `componentSelector`

### ISSUE THREAD

**Issue by davidtheclark** [necolas/postcss-bem-linter#22]
If https://github.com/necolas/postcss-bem-linter/pull/21 is merged, the references throughout to `selector` often no longer apply generally to selectors, but instead apply specifically to *component* selectors (as opposed to utility selectors). So a little renaming ought to be done, probably.

**Comment by necolas** [comment]
sgtm

**Comment by davidtheclark** [comment]
Closed via https://github.com/necolas/postcss-bem-linter/issues/27
