### ISSUE TITLE
Make strict mode default

### ISSUE THREAD

**Issue by davidtheclark** [necolas/postcss-bem-linter#24]
As discussed here: https://github.com/necolas/postcss-bem-linter/pull/13#issuecomment-77946016

Unless anybody objects, it probably makes sense to make strict mode the default, and instead have users manually turn on a loose mode.

Some possibilities:
```
/** @define MyComponent; loose-mode */
/** @define MyComponent: loose */
/** @define:loose MyComponent */
```

**Comment by necolas** [comment]
Perhaps more like FB flow:

```
/** @define MyComponent; weak */
```

**Comment by davidtheclark** [comment]
Sounds good. I was stretching my brain to think of some kind of precedent -- Flow seems as good as any.
