### ISSUE TITLE
NPM Push for new error style

### ISSUE THREAD

**Issue by Kingdutch** [necolas/postcss-bem-linter#26]
Could you bump the version and do an npm publish? In 0.2.0, the old style of errors is used which causes file names to be omitted from error messages. The new style error messages can probably fix this. It's a commit made a few months ago so it would be awesome if we could use it 

:hamster:

**Comment by davidtheclark** [comment]
I'd be in favor of a new release after the current issues are resolved. I wonder if it would be a good time to bump major release: since with the recent changes there's an API, having a major release number would be we could more meaningfully indicate with semver when that API has changed.

**Comment by necolas** [comment]
Before 1.0.0, the expectation is that minor version increases may break the API. I'd think I'd rather we stay at 0.x and iron out any kinks and instability before we're happy for 1.0.0. For example, going to 0.2 gives time for Twitter to use it for a few weeks and for any non-suit projects to try out the linter.

**Comment by davidtheclark** [comment]
Ok, sounds good.

**Comment by Kingdutch** [comment]
A bump to 0.3.0 would probably fit within semver though right? More meaningful error messages seem something worth releasing :)

**Comment by necolas** [comment]
Ah yes I meant 0.3.

**Comment by Kingdutch** [comment]
:+1:

**Comment by davidtheclark** [comment]
@necolas If the pending pull requests work out, I don't have any other particular changes in mind, so would be eager for a new release.

**Comment by necolas** [comment]
let me test master out against our code base before i cut a new release.

**Comment by necolas** [comment]
i dropped HEAD into our codebase and no errors were reported when i introduced them (so our build succeeds when it should).

**Comment by simonsmith** [comment]
A 0.3 release for the latest namespace stuff would be great

**Comment by necolas** [comment]
sorry my comment suggested the opposite of what is happening. master doesn't report errors properly, which is why i haven't cut a new version

**Comment by davidtheclark** [comment]
oh, huh ... errors are logging as PostCSS warnings (as discussed in #32 as #36), which means you'd need to be setup to see those (using [postcss-log-warnings](https://github.com/davidtheclark/postcss-log-warnings) or something). do you have that in place?

**Comment by necolas** [comment]
the docs need to mention that, otherwise the plugin doesn't really do anything for you. so this plugin would be dependent on using 'postcss-log-warnings' too?

**Comment by MoOx** [comment]
It depends on your workflow I guess. If you use webpack for example, you would prefer getting webpack warnings emitted. But yeah, your runner has to show you the messages.

**Comment by davidtheclark** [comment]
I just added a sentence to Readme --- sorry I didn't know that it would just commit automatically without creating PR :)

Also, if it's really important *not* to rely on a runner or plugin to log the warnings, we could probably add an option to this plugin that will exit the process and print those warnings immediately.

**Comment by necolas** [comment]
We currently want the build to fail when the CSS is not properly scoped, otherwise it will end up in master.

The postcss logger plugin worked, but since we're using webpack I end up with 2 sets of warnings – one from postcss, one from webpack. If I use `throwError:true`, it exits with `1` but you can't tell why. It's not obvious that all the warnings printed before are actually the source of the error.

**Comment by MoOx** [comment]
@necolas that why the runner need to emit errors via webpack (eg for eslint: https://github.com/MoOx/eslint-loader#errors-and-warning). This will need to be an option added in postcss-loader

**Comment by davidtheclark** [comment]
I opened #44 to address this.

**Comment by necolas** [comment]
Another thing to discuss. `master` produces warnings for selectors like:

```css
.Button--modifier.Button--anotherModifier {}
```

We have some code like that in a new app. I think that pattern probably _is_ something to avoid, because there are basically side-effects from including 2 modifiers together (should probably be a single modifier). Just wanted to check if there is any disagreement about that.

Thansk

**Comment by davidtheclark** [comment]
Yeah, I agree that it would probably be better to use a single modifier.

**Comment by davidtheclark** [comment]
@necolas Anything else you'd like to see done before a new release?

**Comment by davidtheclark** [comment]
@necolas Any word on this?

**Comment by necolas** [comment]
tried master on our codebase; looked good. published as 0.3.0. thanks for all the great contributions.
