### ISSUE TITLE
Compatibility with postcss-nested

### ISSUE THREAD

**Issue by timkelty** [necolas/postcss-bem-linter#37]
I'm using https://github.com/postcss/postcss-nested

Rules like the following will fail:

```
/** @define Component */

.Component {
  color: blue;

  &.is-active {
    color: red;
  }
}
```

Any chance for adding compatibility?

**Comment by MoOx** [comment]
Why don't you just add you invalid css plugin before the linter ?
That might solve the problem.

**Comment by timkelty** [comment]
Of course! Not sure why I didn't think of that.
Thanks @MoOx
