### ISSUE TITLE
Should ignore files that have no nodes

### ISSUE THREAD

**Issue by joefiorini** [necolas/postcss-bem-linter#38]
I have some less templates that get processed into CSS files but actually output nothing. This gets normalized away eventually when my build process concatenates the individual CSS templates. I have the bem linter processing each individual file, not the final concatenated output, which means sometimes it runs against empty files (eg. less templates that contain _only_ mixins and are not output). This causes an error in the linter because `firstNode` is undefined. Should the linter just ignore any CSS without nodes?

**Comment by joefiorini** [comment]
Note as a workaround I can put a comment in any affected less templates and it gets through the build; but this will be in my final output, so I'd prefer not to do that.

**Comment by simonsmith** [comment]
I solved this in the build pipeline, with something like https://github.com/nahody/gulp-clip-empty-files

**Comment by necolas** [comment]
I believe this is fixed by cecd6fc046154dcb281bf2e290c691cd0e9e6c72
