### ISSUE TITLE
Support namespaces

### ISSUE THREAD

**Issue by simonsmith** [necolas/postcss-bem-linter#39]
Basically the same issue from rework-suit-conformance

https://github.com/suitcss/rework-suit-conformance/issues/7

**Comment by davidtheclark** [comment]
I believe what you're looking for was added to master in https://github.com/necolas/postcss-bem-linter/pull/20, just hasn't been released yet.

**Comment by simonsmith** [comment]
Ah fantastic. Will wait for this. Thanks

**Comment by tforssander** [comment]
Might be off topic but I'm having issues adding namespace to my components (for instance: ns-Excerpt) when using the SUIT CSS preprocessor.

Should this option be added in the SUIT CSS configuration (rules object) or someplace else?

**Comment by simonsmith** [comment]
@tforssander You can pass options to `postcss-bem-linter` via the SUIT preprocessor. Let me know if have issues.

**Comment by tforssander** [comment]
@simonsmith Ah, make sense! Solved it by doing it like this:

```
# suitcss-config.js
module.exports = {
  'postcss-bem-linter': {
    preset: 'suit',
    presetOptions: {
      namespace: 'twt'
    }
  }
```

Thanks for the quick reply once again!

**Comment by simonsmith** [comment]
Excellent 👍
