### ISSUE TITLE
Pseudo class on utility reports as an error

### ISSUE THREAD

**Issue by simonsmith** [necolas/postcss-bem-linter#45]
Using this rule I get a failure message:

``` css
.u-linkMuted:hover {
  /* declarations */
}
```
``` bash
6:3	Invalid utility selector ".u-linkMuted:hover" [postcss-bem-linter]
```

As far as I know pseudo classes on utilities are allowed, seen [here in suitcss-utils-link](https://github.com/suitcss/utils-link/blob/master/lib/link.css) for example

**Comment by davidtheclark** [comment]
I'm curious if the problem you're having is with the latest release or with master?

I think I tried in the unreleased master code to solve that here: https://github.com/necolas/postcss-bem-linter/blob/master/lib/is-valid-selector.js#L77

**Comment by simonsmith** [comment]
Hmm, I am using master. Not sure how old it is. Will update

**Comment by davidtheclark** [comment]
OK. If it's still there after updating then it's a bug :)

**Comment by simonsmith** [comment]
Still seeing it. Perhaps allow `:` in the second character class here? - https://github.com/necolas/postcss-bem-linter/blob/master/lib/preset-patterns.js#L11

**Comment by davidtheclark** [comment]
Oh I see ... dumb mistake. The handling of pseudos is applying to component selectors but not utility selectors. I will fix quick.

**Comment by simonsmith** [comment]
Thanks for the fix on this.

Any chance we can get this merged with a new tag? Would be good to not install `master` as a dependency.

**Comment by davidtheclark** [comment]
Other than that bug, has master been working as expected for you?

**Comment by simonsmith** [comment]
Yeah, using it on a couple projects at the moment. Main reason to use master right now is for the namespace support. All seems good.

**Comment by davidtheclark** [comment]
Well, I just merged the PR into master. We'll see about a release cc/ @necolas
