### ISSUE TITLE
Support for custom class convention regexes?

### ISSUE THREAD

**Issue by davidtheclark** [necolas/postcss-bem-linter#6]
Are you open to supporting user-defined regular expressions that define custom class naming conventions?

The name of the module would make less sense in that case (i.e. user's convention might not be BEM or BEMish) --- but it doesn't seem like it would be too hard to allow for the flexibility in this codebase.

*Or* do you think such an idea is fodder for a separate module?

(I would like to try to work on a pull request to this module, or start up a separate module, to make this happen.)

**Comment by necolas** [comment]
Yes. See #1 and #2
